### ISSUE TITLE
--output-dir not working in v0.5.0

### ISSUE THREAD

**Issue by kmalaver** [hay-kot/scaffold#243]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.

### What is the issue you are experiencing?

In the last version the flag --output-dir is not working, the project is generated in the local path

### Steps to Reproduce (or failing test case)

run  `scaffold new example --output-dir='"./my/custom/path" `                 

### Scaffold Version (`scaffold --version`)

v0.5.0

**Comment by hay-kot** [comment]
This still works for me, the issue is with your command order I believe. It should be 

```shell
run scaffold new --output-dir='"./my/custom/path" example 
```

Which is dumb, but it's a limitation of the CLI library I'm using. [They've fixed this in v3](https://github.com/urfave/cli/issues/1950) which is in pre-release right now.

I'm going to look into migrating to v3 over Christmas when I have some time off and have time for a nice refactor 😄

**Comment by kmalaver** [comment]
it was indeed the order, thank you 🙌
